name: 🐧Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo add-apt-repository universe && sudo apt-get update
    - name: update-premake
      run: sudo add-apt-repository ppa:beauman/marley && sudo apt-get update
    - name: Vulkan-SDK
      run: wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - && sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list && sudo apt update

    - name: getdeps
      run: sudo apt install premake5 git build-essential xorg-dev libxrandr-dev libvulkan-dev vulkan-sdk  libpulse-dev libibus-1.0-dev libglib2.0-dev libsamplerate0-dev libasound2-dev libudev-dev

    - name: submodules
      run: git submodule update --init --recursive

    - name: premake
      run: premake5 gmake2

    - name: compile (release)
      run: export MAKEFLAGS=-j8 && make verbose=1 config=release

    - name: clean release folder
      run: rm -f bin/Release/libresource-system-gnu.a

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
            name: engine-linux
            path: bin/Release
